// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrpn0p3YKyU-u3CSf2D3qYDUShY1i-SjY',
    appId: '1:82670914417:web:1e1a8ebe16b2a7879d44d0',
    messagingSenderId: '82670914417',
    projectId: 'movie-app-2a89b',
    authDomain: 'movie-app-2a89b.firebaseapp.com',
    storageBucket: 'movie-app-2a89b.appspot.com',
    measurementId: 'G-48NS50JVMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-24KcWYIoyfwrAaveyhXnoCROvXMxT0g',
    appId: '1:82670914417:android:02e2eed294d562b39d44d0',
    messagingSenderId: '82670914417',
    projectId: 'movie-app-2a89b',
    storageBucket: 'movie-app-2a89b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGayhNHjQ-9nKx6EhMezlGq15ahIi78ww',
    appId: '1:82670914417:ios:5227dcab9eb7f2109d44d0',
    messagingSenderId: '82670914417',
    projectId: 'movie-app-2a89b',
    storageBucket: 'movie-app-2a89b.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGayhNHjQ-9nKx6EhMezlGq15ahIi78ww',
    appId: '1:82670914417:ios:5227dcab9eb7f2109d44d0',
    messagingSenderId: '82670914417',
    projectId: 'movie-app-2a89b',
    storageBucket: 'movie-app-2a89b.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrpn0p3YKyU-u3CSf2D3qYDUShY1i-SjY',
    appId: '1:82670914417:web:9abff38469d190f09d44d0',
    messagingSenderId: '82670914417',
    projectId: 'movie-app-2a89b',
    authDomain: 'movie-app-2a89b.firebaseapp.com',
    storageBucket: 'movie-app-2a89b.appspot.com',
    measurementId: 'G-2FPDH8V9B3',
  );
}
